name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: macOS-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v2
    - name: Force XCode 11.6
      run: sudo xcode-select -switch /Applications/Xcode_11.6.app
    - name: Build
      run: swift buid -v
    - name: Run tests
      run: swift test -v
