name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: macOS-latest

    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.6,name=iPhone 11']
        xcode: ['/Applications/Xcode.app/Contents/Developer']

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: bundle exec fastlane scan --destination "${destination}" --scheme "YOUR-SCHEME"
    - name: Run tests
      run: swift test -v
